In [ ]:
#data cleaning

In [ ]:
import pandas as pd
data = pd.read_excel("/content/employee_data_10x9.xlsx")
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,NaN,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,NaN,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,NaN,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,NaN,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,NaN
7,E008,Meena,30.0,HR,NaN,6.0,Mysore,Female,87.0
8,E009,Vijay,NaN,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,NaN,Female,89.0

In [ ]:
data.isnull()

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,False,True
7,False,False,False,False,True,False,False,False,False
8,False,False,True,False,False,False,False,False,False
9,False,False,False,False,False,False,True,False,False

In [ ]:
data.isnull().sum()

Employee_ID    0
Name           0
Age            2
Department     0
Salary         2
Experience     1
City           2
Gender         0
Performance    1
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(8)

In [ ]:
data['City']=data['City'].fillna('Mangalure')
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,NaN,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,NaN,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,NaN,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,NaN
7,E008,Meena,30.0,HR,NaN,6.0,Mysore,Female,87.0
8,E009,Vijay,NaN,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data['Age']=data['Age'].fillna(24)
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,NaN,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,NaN,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,NaN
7,E008,Meena,30.0,HR,NaN,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data['Salary']=data['Salary'].fillna(50000)
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,NaN,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,NaN
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data['Experience']=data['Experience'].fillna(8)
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,NaN
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data['Performance']=data['Performance'].fillna(90)
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Experience     0
City           0
Gender         0
Performance    0
dtype: int64

In [ ]:
data['Age']=data['Age'].fillna(30)
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Experience     0
City           0
Gender         0
Performance    0
dtype: int64

In [ ]:
data.isnull().duplicated()

0    False
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
dtype: bool

In [ ]:
data.isnull().duplicated().sum()

np.int64(9)

In [ ]:
data.isnull().drop_duplicates()
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Experience     0
City           0
Gender         0
Performance    0
dtype: int64

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data['Name']=data['Name'].str.strip()
data

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
df = data.drop_duplicates()
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
df['City']=df['City'].str.strip()
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24.0,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27.0,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24.0,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25.0,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31.0,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26.0,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28.0,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30.0,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24.0,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27.0,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
#import numpy as np
#df.loc[df['Age'] > 80, 'Age']=np.nan
#df
df.dtypes

Employee_ID     object
Name            object
Age            float64
Department      object
Salary         float64
Experience     float64
City            object
Gender          object
Performance    float64
dtype: object

In [ ]:
df['Age']  = df['Age'].astype(int)
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24,IT,35000.0,1.0,Bangalore,Male,85.0
1,E002,Priya,27,HR,42000.0,3.0,Mysore,Female,90.0
2,E003,Arun,24,Finance,50000.0,5.0,Bangalore,Male,78.0
3,E004,Sneha,25,IT,50000.0,2.0,Hubli,Female,88.0
4,E005,Kiran,31,Marketing,55000.0,8.0,Dharwad,Male,92.0
5,E006,Anjali,26,IT,41000.0,3.0,Mangalure,Female,81.0
6,E007,Rohit,28,Finance,48000.0,4.0,Bangalore,Male,90.0
7,E008,Meena,30,HR,50000.0,6.0,Mysore,Female,87.0
8,E009,Vijay,24,IT,32000.0,1.0,Hubli,Male,75.0
9,E010,Neha,27,Marketing,46000.0,4.0,Mangalure,Female,89.0

In [ ]:
df['Salary']  = df['Salary'].astype(int)
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24,IT,35000,1.0,Bangalore,Male,85.0
1,E002,Priya,27,HR,42000,3.0,Mysore,Female,90.0
2,E003,Arun,24,Finance,50000,5.0,Bangalore,Male,78.0
3,E004,Sneha,25,IT,50000,2.0,Hubli,Female,88.0
4,E005,Kiran,31,Marketing,55000,8.0,Dharwad,Male,92.0
5,E006,Anjali,26,IT,41000,3.0,Mangalure,Female,81.0
6,E007,Rohit,28,Finance,48000,4.0,Bangalore,Male,90.0
7,E008,Meena,30,HR,50000,6.0,Mysore,Female,87.0
8,E009,Vijay,24,IT,32000,1.0,Hubli,Male,75.0
9,E010,Neha,27,Marketing,46000,4.0,Mangalure,Female,89.0

In [ ]:
df['Gender'] = df['Gender'].replace({"M" : "Male","F" : "Female"})
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Gender,Performance
0,E001,Rahul,24,IT,35000,1.0,Bangalore,Male,85.0
1,E002,Priya,27,HR,42000,3.0,Mysore,Female,90.0
2,E003,Arun,24,Finance,50000,5.0,Bangalore,Male,78.0
3,E004,Sneha,25,IT,50000,2.0,Hubli,Female,88.0
4,E005,Kiran,31,Marketing,55000,8.0,Dharwad,Male,92.0
5,E006,Anjali,26,IT,41000,3.0,Mangalure,Female,81.0
6,E007,Rohit,28,Finance,48000,4.0,Bangalore,Male,90.0
7,E008,Meena,30,HR,50000,6.0,Mysore,Female,87.0
8,E009,Vijay,24,IT,32000,1.0,Hubli,Male,75.0
9,E010,Neha,27,Marketing,46000,4.0,Mangalure,Female,89.0

In [ ]:

data=df

In [ ]:
print(df.columns)

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Experience',
       'City', 'Performance', 'Gender_Female', 'Gender_Male'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip()
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Performance,Gender_Female,Gender_Male
0,E001,Rahul,24,IT,35000,1.0,Bangalore,85.0,False,True
1,E002,Priya,27,HR,42000,3.0,Mysore,90.0,True,False
2,E003,Arun,24,Finance,50000,5.0,Bangalore,78.0,False,True
3,E004,Sneha,25,IT,50000,2.0,Hubli,88.0,True,False
4,E005,Kiran,31,Marketing,55000,8.0,Dharwad,92.0,False,True
5,E006,Anjali,26,IT,41000,3.0,Mangalure,81.0,True,False
6,E007,Rohit,28,Finance,48000,4.0,Bangalore,90.0,False,True
7,E008,Meena,30,HR,50000,6.0,Mysore,87.0,True,False
8,E009,Vijay,24,IT,32000,1.0,Hubli,75.0,False,True
9,E010,Neha,27,Marketing,46000,4.0,Mangalure,89.0,True,False

In [ ]:
import pandas as pd

data = pd.get_dummies(data, columns=['Gender'], dtype=int)

data

KeyError: "None of [Index(['Gender'], dtype='object')] are in the [columns]"

In [ ]:
print(df.columns.tolist())

['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Experience', 'City', 'Performance', 'Gender_Female', 'Gender_Male']

In [ ]:
print(df[['Gender_Female', 'Gender_Male']])

   Gender_Female  Gender_Male
0          False         True
1           True        False
2          False         True
3           True        False
4          False         True
5           True        False
6          False         True
7           True        False
8          False         True
9           True        False

In [ ]:
df[['Gender_Female', 'Gender_Male']] = df[['Gender_Female', 'Gender_Male']].astype(int)
df

,Employee_ID,Name,Age,Department,Salary,Experience,City,Performance,Gender_Female,Gender_Male
0,E001,Rahul,24,IT,35000,1.0,Bangalore,85.0,0,1
1,E002,Priya,27,HR,42000,3.0,Mysore,90.0,1,0
2,E003,Arun,24,Finance,50000,5.0,Bangalore,78.0,0,1
3,E004,Sneha,25,IT,50000,2.0,Hubli,88.0,1,0
4,E005,Kiran,31,Marketing,55000,8.0,Dharwad,92.0,0,1
5,E006,Anjali,26,IT,41000,3.0,Mangalure,81.0,1,0
6,E007,Rohit,28,Finance,48000,4.0,Bangalore,90.0,0,1
7,E008,Meena,30,HR,50000,6.0,Mysore,87.0,1,0
8,E009,Vijay,24,IT,32000,1.0,Hubli,75.0,0,1
9,E010,Neha,27,Marketing,46000,4.0,Mangalure,89.0,1,0